tailscale_auth_key: ENC[AES256_GCM,data:KwpPTlByB65ZgW/XrtnPK9x5eyTl,iv:uGyJiAhwr5U7dPcH0K35RgFH9wl54Dix0BahWbER0bw=,tag:hoqebO8Lc+SC31H2Gtv6oA==,type:str]
sops:
    age:
        - recipient: age1uhgqfcm3tfuzv3tq8d62medf04g977zas2hr9wmntc8wjn2e3asqvp7adp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmOXNtRlY4K2xtaGxFRGE0
            cHY4NTR3djFHdCsvYnZrTFNEQW16L0U0clRvCnpZWCtna2NuS3F0SmdpdkgzU3hB
            bWRXQWI4ZFpWeXhnSkNYNmNyM0Z5KzAKLS0tIGlJaTlXNXpzRjlITWhvUmROcFdV
            OG5xbFhFSWkrdzRLMEdmNi9wS2VBUm8KzFj5L35cZkr0NiZxvrz4BaPGDQb7/Kmo
            KGnE0dGksvkM2iDYPai+z3WWbfRskEO2azfxUck6mSAIkPx1fnc5bA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-09T20:39:09Z"
    mac: ENC[AES256_GCM,data:E8gs78YHuFQKAJ3+sVcteSPIMZMKgHx0H7LOFTM8LWfv5heM4Cu2gdhclZLHiVfMjSpFeoQ5OtybrRvL7p0tqtOx0VaU8SfgTRFLGrM1/EgRyvmboAiurBsivBFHzb6ftbXPz6cQPgXMsCiFvfp7dj+khbks2rB4DT433AyWXX8=,iv:u9RlGSdVqHB+BFu2/phqH+51erMt5qxzdhpjMDFTNCg=,tag:/S7/KcwBntEXpEdpCXC+xQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
