tailscale_auth_key: ENC[AES256_GCM,data:g8cNkJHjtTELDwYt6Bv5QxCc+89JHJS5xkyS6QnrAT/4kmC7jzP873B7Pjs+IZ6aCF5wyZVBkn8H9Y6kRKs=,iv:BEpnMTVGaGXNohgGmciSL2VSGO3r/kE1QiAWGvrOblI=,tag:SfLi9cZaDE+dwXDsM7Uung==,type:str]
sops:
    age:
        - recipient: age1uhgqfcm3tfuzv3tq8d62medf04g977zas2hr9wmntc8wjn2e3asqvp7adp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmOXNtRlY4K2xtaGxFRGE0
            cHY4NTR3djFHdCsvYnZrTFNEQW16L0U0clRvCnpZWCtna2NuS3F0SmdpdkgzU3hB
            bWRXQWI4ZFpWeXhnSkNYNmNyM0Z5KzAKLS0tIGlJaTlXNXpzRjlITWhvUmROcFdV
            OG5xbFhFSWkrdzRLMEdmNi9wS2VBUm8KzFj5L35cZkr0NiZxvrz4BaPGDQb7/Kmo
            KGnE0dGksvkM2iDYPai+z3WWbfRskEO2azfxUck6mSAIkPx1fnc5bA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-09T20:49:12Z"
    mac: ENC[AES256_GCM,data:M+NxkmZGeSL7kfNbNiMMOlk183IG9+jVPxFPt0YUnU2KpCUyKHVy5MPlrxtTrW4HgIt6CExnQCeOcfek/A4/BuFHXudPQvbRJpeH1VabTEogzm8C7YSa6s0byi/kEcH/ZIAkmOO4GaUp+BFAUZWlrBoIXwQlHhZSp06MhCk8Xrw=,iv:skJdR/sdav1hnrA9MrEYIpSGLZXs2WI0X/KDUw102oM=,tag:MQlQs7sFgLtWSdgA5ArbCQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
